# Generated by Django 4.2 on 2024-11-29 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_subscribe",
            field=models.BooleanField(
                blank=True,
                default=False,
                null=True,
                verbose_name="Подписка на напоминания",
            ),
        ),
    ]
